<!-- Begining of wordpig.php -->
<?php

$quotes = array(
"Almost-There, driving you're gaming addiction... One game at a time!",
"She is offending my thinkin' words with her talkin' brains",
"I said whale jine ??",
"We know what It feels like to chew five gum...",
"On this website, we have to use the clearfix hack",
"Time to Adventurize",
"We, will be the wonder of wonderland",
"You may now proceed to hack the planet",
"Begining simulation in 3... 2... 1...",
"Who are you people?! I don't know...",
"Every card in our deck is a trap card",
"I shot Yahoo, but I did no shoot...",
"Do you have any idea how to forge a will?",
"its going to fry my little ADD filled brain",
"I forget to think about my face",
"It makes the clicky noises",
"Almost Where? We don't know",
"In colour!",
"In hypno-vision",
"As seen on TV",
"Presented in BC [BRAIN CONTROL] where available",
"Featuring gratuitious alien nudity",
"Presented in Double Vision (Where Drunk)",
"Condemmed by [Redacted]",
"Filmed on location",
"Proudly Made On Earth",
"Made from Meat By-Products &copy;",
"Based on a true story",
"The website that watches you back",
"Not based on the novel",
"This website has been modified to fit your primative screen",
"As fortold by Nostradamus",
"A stern warning of things to come",
"Simulcast on crazy people's fillings",
"Larva-Tested Pupa-Approved",
"For external use only",
"Do not inhale",
"Touch eyeballs to screen for cheap laser surgery",
"Now presented in Smell-O-Vision.. Insert Nostril tubes now!",
"Not a substitute for human interaction",
"If not entertaining, write your congressmen",
"Torn from tommorow's headlines",
"Deciphered from crop circles",
"Krafted with luv",
"Federal Law prohibits visiting this site...",
"For proper viewing, take the red pill now!",
"Scratch here to reveal prize",
"Love it or shove it!",
"If accidentally viewed, Induce vomiting",
"Soon to be a major religion",
"OR IS IT",
"Controlling you with a chip in your butt since 1999",
"Known to cause insanity in laboratory mice",
"Voted ''Best''",
"Transmitido en Maid en SAP",
"Those hands aren't greasy, they are well lubricated",
"We had an issue earlier with these bunnies jumping all the place. We called Hugh Heffner and had them picked up",
"Your pediatrician told us EVERYTHING",
"Does anyone remember how many horsemen of the apocolypse there were? I want to make sure we have enough hay",
"Just 69 more Smoots to go ",
"You Lost",
"Cyber Terrorisum is the name, pretending we know what we're doing is the game.",
"There has been a security breach, quick someone dial 404!",
"I was going to tell a joke about anger management, but FUCK YOU",
"Came 4 the tits... Came 2 the tits...",
"I was in a public restroom when I wrote down this quote",
"I had a napkin with a ton of quotes scribbled on it, but I fucking lost it",
"Trust me, in a minute sexy things will happen",
"I think they found the first body",
"You know you want some of this fruit's punch",
"Hey man, do you have chlamydia?",
"Every time you smoke, you turn 0.005% more black",
"I know the website is sexy but get your damn hand out of your pants!",
"My skateboard is still in evidence...",
"Self aware roomba is looking for a panty shot",
"Please wait while we sharpen our sporks",
"Stop lurking, fucking post something already!",
"It was the moon, he was paying us to kill sunshine!",
"It was a night to remember, Too bad I forgot it all",
"Almost to your mom's house.. She's cooking dinner",
"Ever done nyquil shots and pass out in the locker room?<br />Its not that awesome but it still makes you look cool",
"Why do you close your eyes when we make love?",
"We never should have sold our patents for the shake weight",
"If you can read this, something is wrong...<br /> UNIVERSAL ERROR 80224!",
"This website is for educational purposes only",
"dahhhh dahhh da dah dah da daduhduh dahh dah dahh<br />My prince is dead... all is lost without him... may god unite us in heaven.",
"Our mind missles are breaking down your defences",
"Always baked<br />Never fried",
"This isn't where I parked my car",
"I don't know if there are any more slogans",
"This place kinda reminds me of defcon",
"Macoshistic doesnt even begin to describe",
"Ruby on Rails; the 'on rails' part would make you think that its an easy ride... but NOOOOO",
"You have a dream in which you are approached in your bed by a very<br />fat man wearing a ballerina's outfit and a pair of paper wings on his back<br />He says: 'Youse no got no teeth, ill be back later'",
"Just shove your face right in!",
"Online Interactions not rated by the ESRB",
"and THIS is why you don't put 14 pounds of gorilla snot in a microwave!",
"Ohhhh myyy!",
"I can't tell if I want you to stay or run away screaming",
"You're being worthless right now",
"Dirty Filthy Cheating Ginger",
"Leakage is a common side effect",
"Free video games!!! <br />Please enter your steam username and password below...",
"That sound you just heard? That's us sneaking in...",
"Don't worry, you'll smell it in a minute",
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL ",
"Wanna play hide and seek? We don't",
"Almost... Impressive...",
"Good people don't end up here...",
"#ALMOST-THERE Tweet it now!",
"If I were you i'd be leaving...",
"Ask about movienights!",
"Are we there yet?",
"Node Access Granted: Thank you for not Hacking",
"This text is dynamic! Kinda...",
"Just wait until there are no witnessess...",
"Our knives are dull, we want you to feel it.",
"Open wide!",
"You look mighty delicous today...",
"This text is very texty",
"Please enter your beautiful people's ID number <br / for the real website",
"Looks like weight watchers failed",
"You feel us judging you right now? Because we are",
"Its at the top of every chat box but you still gave them your password!",
"We don't take kindly to your kind around these parts",
"Ever seen that movie the crying game? Yeah, kinda like that",
"In no way affilated with the band", 
"Maybe we're born with it, maybe its maybelline",
"Don't go walking on sunshine now, or he'll give you cancer",
"The old christian band is definately regretting letting thier domain name expire",
"10,000 Years from now they'll think back on our website<br />and go 'Yep, thats when it started'",
"If we are rubber and you are glue then perhaps what we say about us<br />bounces back to you?",
"If sticks and stones can break your bones and names will never hurt you,<br />We have pipes and knives to cut you",
"Don't mess with us, we know the count, That's right ''THE'' count!", 
"Ehhhh.... your mom", 
"I wish I could CTRL+F my life", 
"Over 1 Buhgillion sold", 
"I'm smiling, that alone should scare you!",
"I thought I had seen the pinnacle of stupid then I met you",
"I'd agree with you, but then we'd both be wrong", 
"Did the aliens tell you that when you took off your foil hat?", 
"EVERYONE STFU, I THINK I HEARD THE ICE CREAM TRUCK!", 
"Stop laughing, we do the best we can!", 
"Covered in more blood than John F Kennedy's wife in a convertable!", 
"It is now the approprate time to SHAZAM!", 
"My imaginary friend says that you need a therapist", 
"The simulation will begin in 3... 2... 1...",
"What are you going to do with your 72 virgins?",
"They tell me to... Burn things..", 
"I have some advice for you<br />Stay Sexy!", 
"We will be waiting for you...<br />In the test chamBURRRRRR...",
"The game your kids are playing", 
"Does this smell like chloriform?", 
"I just figured it out Kenny's real name is &#9630;&#9630;&#9629;&#9627;&#9631;&#9632;<!-- Actually its Andy, Sorry Kenny :P --> ", 
"Secretly uploading pictures of you...", 
"If you are from the FBI or CIA, Welcome!<br />Make sure to get the email and IP addresses of everyone!", 
"This slogan requires an Almost-There GOLD account<br />Please enter credit card information below", 
"This confirms that the tracking cookie we installed is working", 
"Because facebook is too mainstream", 
"This is not web 2.0, it isn't metro, we arn't sure wtf this design is... but its sexy", 
"Go outside and wave at the sky so I can see<br />you on Google Earth", 
"Shame on Cisco, And I'm not talking about the<br />captian of deep space nine.",
"New Goal: Get laid before Kenny's dad",
"4chan won't even fuck with us", 
"Protected by CloudFlare!<br />because we need it...",
"Like Cuba, but with respawn!",
"That was just sheer thirst, it had nothing to do with alcoholism",
"SOPA doesn't know shit", 
"If Jesus calls, We aren't here",
"Too busy playing TF2 to see your probation officer",
"This website uses cookies to store data on your computer, I'm okay with this",
"... And the hidden bonus Track!",
"By the time you read this you've already read it",
"Kenny and Orca sittin in a tree",
"Someday love will find you",
"So here we are again. It's always such a pleasure!",
"scratch here to reveal today's status!",
"scratch here to reveal today's winner!",
"Open 24 hours a day, 7 days a week at Almost-There.org!",
"crap on a cracker!",
"we make this look good!",
"always keep a backup of the live environment!",
"the cake is ALWAYS a lie",
"If the laws of physics do not not apply in the future, god help you!",
"sarcasm self-test complete *boop*",
"We're sort of like 7-Eleven - We're not always doing business, But we're always open.");

$rQuote = rand(0,count($quotes)-1);
$quote = $quotes[$rQuote];
/* Begin the NSFW quotes (Oh baby!) 
"A Sexual Explosion!", 
"Daddy needs some lovin'", 
"You have reached ''Bitch Status'",
"Its not art... its porn...",
"I'm the coat hanger in your man's vagina",
"Customer retention was never one of our<br />strong suits, thats why we invested in these nifty shackles and handcuffs!",
"Squeezing babies to harvest their love", 
"No tresspassing, prosecutors will be violated",
"Banging flashlights before they got vaginas", 
"If you can see your penis, you're doing it wrong",
"Our balls touch the ground, jealous?<br />Don't be, we're sitting",
"One whore? That's one penis too many",
"Assume the position", 
"We mash our penises together monthly, come join<br /> the fun!",
"Wanna play hide and go fuck yourself?",
"Thinking about you.. dead...",
"Bad ass? You havn't seen anything yet",
"Bloody fucking lies... We couldn't be further away",
"Don't piss us off; We're running out of places to hide the bodies",
"Well at least your mom thinks you're pretty",
"Fuck off, Santa Claus  Doesn't know shit!",
"If that's your penis then this is our website",
"It's as easy as anal",
"Crying only makes us want to rape you more",
"Coming soon: Go fuck yourself by Almost There",
"Click here for nude pictures of your mom (you sicko)",
"Fuck have any of you seen my keys?",
"Yes bisexuality is required here, we don't have a lot of women",
"They have a word for us, it rhymes with runts",
"Penis stuck? Yeah, Same here",
"Therapist = The Rapist",
"Anal is for winners, so bottoms up, you lost!",
"Meanwhile in Africa",
"Rock, Paper, Scissors, Rape",
"We are there when you pee...",
"Sweating more than a pedophile in preschool",
"This website used to be made with Flash<br />then Apple really fucked us over",
"Since when does your mom own a meat grinder?<br />    Wait... oh.... NVM",
"Sorry...<br />But you're going to have to bunk with Leslie Nielsen",
"Jesus christ on a stick",
"I have a friend in japan",
"Taste the rainbow motherfucker",
"Fuck buddies should be a relationship status",
"Runs as smooth as a waxed baby's ass" ,
"For when you're scared and your mom is hitting the sauce",
"That minority over there using a bike must have bought it himself.",
"Free baby with purchase!",
"That white stuff all over your convertable's seats isn't bird poop...",
"Have you seen Jesus?<br />Yeah I saw him yesturday and he was pissed!",
?>